import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { logActivity, listActivity } from "@/lib/domain/activity";

describe.skipIf(!process.env.SUPABASE_SERVICE_ROLE_KEY)("logActivity / listActivity", () => {
  const supabase = createSupabaseAdminClient();
  let companyId: string;
  let actorAuthUserId: string;
  let actorProfileId: string;
  const entityId = crypto.randomUUID();

  beforeAll(async () => {
    const { data: company, error: companyError } = await supabase
      .from("companies")
      .upsert({ name: "Test Co (activity)", slug: "test-co-activity" }, { onConflict: "slug" })
      .select("id")
      .single();
    if (companyError) throw companyError;
    companyId = company.id;

    const { data: authUser, error: authError } = await supabase.auth.admin.createUser({
      email: `activity-test-${crypto.randomUUID()}@example.com`,
      password: "password123",
      email_confirm: true,
    });
    if (authError || !authUser.user) throw authError;
    actorAuthUserId = authUser.user.id;

    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .insert({
        auth_user_id: actorAuthUserId,
        company_id: companyId,
        full_name: "Activity Test User",
        role: "employee",
      })
      .select("id")
      .single();
    if (profileError) throw profileError;
    actorProfileId = profile.id;
  });

  afterAll(async () => {
    await supabase.from("activity_log").delete().eq("entity_id", entityId);
    await supabase.from("profiles").delete().eq("id", actorProfileId);
    await supabase.auth.admin.deleteUser(actorAuthUserId);
    await supabase.from("companies").delete().eq("slug", "test-co-activity");
  });

  it("logs an entry and lists it back in chronological order", async () => {
    const first = await logActivity("task", entityId, actorProfileId, "Task created");
    const second = await logActivity("task", entityId, actorProfileId, "Status changed");

    expect(first.message).toBe("Task created");
    expect(first.actorId).toBe(actorProfileId);

    const entries = await listActivity("task", entityId);
    expect(entries.map((e) => e.id)).toEqual([first.id, second.id]);
  });

  it("supports a null actorId for system-generated entries", async () => {
    const entry = await logActivity("task", entityId, null, "Auto-generated by workflow");
    expect(entry.actorId).toBeNull();
  });
});
